# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ctxt',
                'doc_host': 'https://civvic.github.io',
                'git_url': 'https://github.com/civvic/ctxt',
                'lib_path': 'ctxt'},
  'syms': {'ctxt.core': {'ctxt.core.foo': ('core.html#foo', 'ctxt/core.py')}}}
